# -*- mode: ruby -*-
# vi: set ft=ruby :
BRIDGED_NET="192.168.1."
DOMAIN=".home.local"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #config.ssh.username = 'vagrant'
  #config.ssh.password = 'vagrant'
  #config.ssh.remote_user = 'root'
  config.ssh.insert_key = false
  #####################
  # Oracle Linux 7 vm #
  #####################
  config.vm.define "ol7", autostart: false do |ol7|
   ol7.vm.box = "oraclelinux/7"
   ol7.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
   # Hostname который будет присвоен VM (самой ОС)
   ol7.vm.hostname = "ol7" + DOMAIN
   # Add Bridged Network + задать ip
   ol7.vm.network "public_network", ip: BRIDGED_NET + "151", bridge: 'Realtek PCIe GBE Family Controller'
   # enable root ssh login
   ol7.vm.provision "shell", inline: <<-SHELL
   sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
   sudo sed -i 's/PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config
   sudo su - root -c 'echo -e "root00\nroot00" | passwd'
   sudo service sshd restart
   SHELL
  end
  ##############
  # Ansible vm #
  ##############
  config.vm.define "ansible", autostart: true do |ubuntu|
   ubuntu.vm.box = "ubuntu/trusty64"
   # Hostname который будет присвоен VM (самой ОС)
   ubuntu.vm.hostname = "ansible" + DOMAIN
   # Add Bridged Network + задать ip
   ubuntu.vm.network "public_network", ip: BRIDGED_NET + "150", bridge: 'Realtek PCIe GBE Family Controller'
   # enable root ssh login
   ubuntu.vm.provision "shell", inline: <<-SHELL
   sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
   sudo sed -i 's/PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config
   sudo su - root -c 'echo -e "root00\nroot00" | passwd'
   sudo service ssh restart
   SHELL
   # Параметры ram
   ubuntu.vm.provider "virtualbox" do |ubuntum|
	ubuntum.memory = 512
   end
   ## Установка Ansible
   ubuntu.vm.provision "shell", inline: <<-SHELL
   # fix error dpkg-preconfigure: unable to re-open stdin: No such file or directory
   export DEBIAN_FRONTEND=noninteractive
   # install ansible + git + git clone ansible repository + add configs
   apt-key update && apt-get update && apt-get -y upgrade && apt-get -y install python-software-properties && apt-get -y install software-properties-common && apt-add-repository -y ppa:rquillo/ansible && apt-get update && apt-get -y install ansible
   apt-add-repository ppa:ansible/ansible -y
   apt-get update
   apt-get install ansible -y
   apt-get install git -y
   sudo su - -c "git clone https://github.com/vfedotov1/Common.git && mv Common/ansible ./ && rm -rf Common/"
   SHELL
   # add following lines to bash profile to change default config locations
   ubuntu.vm.provision "shell", inline: <<-SHELL
   sudo su - -c 'cat << EOF >> ~/.bash_profile
yellow="\\\\033[0;33m"
Color_Off="\\\\033[0m"
export ANSIBLE_CONFIG=/root/ansible/ansible.cfg
export ANSIBLE_PLAYBOOK_DIR=/root/ansible/playbooks
# export ANSIBLE_LIBRARY=/srv/modules/custom_modules:/srv/modules/vendor_modules
echo "##############################################################################"
test "x\\${ANSIBLE_CONFIG}" = 'x' || echo "## ANSIBLE_CONFIG=\\${ANSIBLE_CONFIG}"
test "x\\${ANSIBLE_PLAYBOOK_DIR}" = 'x' || echo "## ANSIBLE_PLAYBOOK_DIR=\\${ANSIBLE_PLAYBOOK_DIR}"
echo -e "##\\n################# ANSIBLE_CONFIG #################"
cat \\$ANSIBLE_CONFIG | while read LINE; do echo -e "## \\${yellow}\\${LINE}\\${Color_Off}"; done
echo "##############################################################################"
EOF'
  SHELL
  end
 # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "oraclelinux/7"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
