CREATE TABLE SYSTEM.TABLE_GROWTH
(
  ID                    NUMBER(20) GENERATED ALWAYS AS IDENTITY ( START WITH 3441 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  TIME                  DATE                    NOT NULL,
  OWNER                 VARCHAR2(20 BYTE),
  TABLE_NAME            VARCHAR2(30 BYTE),
  TABLE_SIZE            NUMBER(20),
  GROWTH_IN_MB_PER_DAY  NUMBER(20)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


-- Sequence ISEQ$$_1450394 is created automatically by Oracle for use with an Identity column


CREATE UNIQUE INDEX SYSTEM.TABLE_GROWTH_PK ON SYSTEM.TABLE_GROWTH
(ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER SYSTEM.TABLE_GROWTH_TRG
  BEFORE INSERT ON system.table_growth
  FOR EACH ROW
BEGIN
  :new.time := sysdate;
END;
/


ALTER TABLE SYSTEM.TABLE_GROWTH ADD (
  CONSTRAINT TABLE_GROWTH_PK
  PRIMARY KEY
  (ID)
  USING INDEX SYSTEM.TABLE_GROWTH_PK
  ENABLE VALIDATE);
